version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: goapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
      MYSQL_USER: catalog
      MYSQL_PASSWORD: catalog
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
